server:
  port: 5000
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  datasource:
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  output:
    ansi:
      enabled: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      default_batch_fetch_size: 100 # in query 자동 작성
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    '[com.example.buva]': DEBUG
    '[org.hibernate.orm.jdbc.bind]': TRACE